# Generated by Django 4.2.2 on 2023-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
